version: '3.1'

services:
  web:
    build: 
      context: ./backend
      dockerfile: backend.dockerfile
    command: >
      sh -c "python -Xfrozen_modules=off -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m
      uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    # debugger test config
    # command: >
    #   sh -c "python -Xfrozen_modules=off -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000" # application port
      - "5678:5678" # debug port
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: surfing_data
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: celery -A app.main.celery_app worker --loglevel=info
    depends_on:
      - web
      - redis
      
  celery-beat:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    command: celery -A app.main.celery_app beat --loglevel=info
    depends_on:
      - redis

volumes:
  db_data: