"""test migrations

Revision ID: 0f6997de46f3
Revises: 78f19d620643
Create Date: 2024-02-25 00:13:02.013475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6997de46f3'
down_revision: Union[str, None] = '78f19d620643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('test_migration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'test_migration')
    # ### end Alembic commands ###
