"""add location column to spots

Revision ID: 5a37ae229ed3
Revises: 0f6997de46f3
Create Date: 2024-02-25 00:33:06.118820

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a37ae229ed3"
down_revision: Union[str, None] = "0f6997de46f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spots",
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT", srid=4326, from_text="ST_GeogFromText", name="geography"
            ),
            nullable=True,
        ),
    )
    op.execute(
        "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'idx_spots_location') THEN CREATE INDEX idx_spots_location ON spots USING gist (location); END IF; END$$;"
    )

    op.drop_column("spots", "test_migration")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spots", sa.Column("test_migration", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.execute("DROP INDEX IF EXISTS idx_spots_location;")
    op.drop_column("spots", "location")
    # ### end Alembic commands ###
