
on:
  schedule:
    - cron:  '0 7 * * *' # Every day at 2am EST. Ref https://crontab.guru/examples.html

name: Get SL Data
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
            curl -sSL https://install.python-poetry.org | python -
            poetry config virtualenvs.create false

    - name: Install dependencies
      run: poetry install
      
    - name: Run Script
      run: python get_sl_data.py

    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
        BRANCH_NAME: 'main'